[build]
pre-build = ["""
    dpkg --add-architecture $CROSS_DEB_ARCH && \
    apt-get update && apt-get --assume-yes install \
        libgtk-3-dev:$CROSS_DEB_ARCH \
        libssl-dev:$CROSS_DEB_ARCH \
        libasound2-dev:$CROSS_DEB_ARCH
"""]

[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-gnu:edge"

[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:edge"
